"""Test-only byte-construction oracle; imports no Verifier/Protocol helper.

Member fragments and whitespace are chosen before candidate execution. Projection
is assembled by omitting known fragments according to D0, never by scanning the
candidate's output or reserializing its parsed object. hashlib fixes expected
hashes independently of the TS call path (both may share an OpenSSL trust base).
"""
import hashlib
import json
from pathlib import Path
import random
import sys

HERE = Path(__file__).resolve().parent
DOMAIN = b'nomue/record-content/v1\n'

def digest(text):
    return 'sha256:' + hashlib.sha256(DOMAIN + text.encode('utf8')).hexdigest()


def assemble(members, target, lead='', trail='', prefix='', suffix=''):
    # Each member is (whitespace before key, key-through-value, whitespace after value).
    body = [a+b+c for a,b,c in members]
    raw = prefix+'{'+lead+','.join(body)+trail+'}'+suffix
    if target is None:
        projected = raw
    elif target+1 < len(body):
        # Keep the target's leading whitespace, delete through its following comma.
        projected = prefix+'{'+lead+','.join(body[:target])
        if target: projected += ','
        projected += members[target][0]+','.join(body[target+1:])+trail+'}'+suffix
    elif target:
        # Remove preceding comma and member value, preserve target trailing whitespace.
        projected = prefix+'{'+lead+','.join(body[:target])+members[target][2]+trail+'}'+suffix
    else:
        projected = prefix+'{'+lead+members[0][0]+members[0][2]+trail+'}'+suffix
    return raw, projected


def row(name, raw, projection, **extra):
    return {'id':name, 'input':raw, 'projection':projection,
            'digest':digest(projection), **extra}


def full_calls():
    # Decode source token boundaries once using CPython's standard decoder. The
    # retained nested token spelling is never generated by the tested canonicalizer.
    path = HERE.parent/'fixtures/example-record.jcs'
    source = path.read_text().replace('candidate.4', 'candidate.5')
    decoder=json.JSONDecoder(); i=1; parts=[]
    while source[i] != '}':
        start=i; key,i=decoder.raw_decode(source,i); assert source[i]==':'
        _,i=decoder.raw_decode(source,i+1); parts.append((key,source[start:i]))
        if source[i]==',':i+=1
    pos=next(n for n,(k,_) in enumerate(parts) if k=='integrity')
    no_integrity=[v for k,v in parts if k!='integrity']
    expected_projection='{'+','.join(no_integrity)+'}'
    integrity=json.loads(dict(parts)['integrity'].split(':',1)[1])
    integrity['content_digest']=digest(expected_projection)
    parts[pos]=('integrity','"integrity":'+json.dumps(integrity,sort_keys=True,separators=(',',':')))
    tokens=[v for _,v in parts]
    def build(name, seq, target, canonical=False, schema=True, **layout):
        raw,p=assemble([('',v,'') for v in seq],target,**layout)
        checks=({'S':'pass','K':'pass' if canonical else 'fail','D':'pass','H':'pass',
                 'I':'pass' if canonical else 'not_run','C':'pass','A':'pass' if canonical else 'not_run'}
                if schema else {'S':'fail','K':'not_run','D':'not_run','H':'not_run','I':'not_run','C':'not_run','A':'not_run'})
        return row(name,raw,p,checks=checks,forward=canonical and schema,canonical=canonical)
    result=[build('ORACLE-canonical',tokens,pos,canonical=True)]
    result.append(build('ORACLE-first',[tokens[pos]]+no_integrity,0))
    result.append(build('ORACLE-last',no_integrity+[tokens[pos]],len(no_integrity)))
    spaced=[(' \t',v,'\r\n ') for v in tokens]
    raw,p=assemble(spaced,pos,prefix='\n',suffix='\r\n')
    result.append(row('ORACLE-whitespace',raw,p,checks=result[1]['checks'],forward=False,canonical=False))
    escaped=tokens.copy();escaped[pos]=escaped[pos].replace('"integrity"','"\\u0069ntegrity"',1)
    result.append(build('ORACLE-escaped-key',escaped,pos))
    result.append(build('ORACLE-newline',tokens,pos,suffix='\n'))
    result.append(build('ORACLE-absent',no_integrity,None,canonical=True,schema=False))
    nested=tokens+['"oracle_note":{"integrity":["日本語😀é","quote \\\" , }",{"x":"\\u0061"}]}']
    result.append(build('ORACLE-nested-unicode',nested,pos,schema=False))
    numeric=tokens.copy();idx=next(n for n,(k,_) in enumerate(parts) if k=='payload')
    assert '"value":1' in numeric[idx];numeric[idx]=numeric[idx].replace('"value":1','"value":1.0e+0',1)
    result.append(build('ORACLE-number-spelling',numeric,pos))
    bad=tokens.copy();bad[pos]=bad[pos].replace(integrity['content_digest'],'sha256:'+'0'*64)
    r=build('ORACLE-declared-digest',bad,pos,canonical=True)
    r['checks']['I']='fail';r['checks']['A']='not_run';r['forward']=False
    result.append(r)
    # Only an input-assembly sanity check, not the expected projection algorithm.
    for r in result:
        parsed=json.loads(r['input']);parsed.pop('integrity',None)
        assert parsed==json.loads(r['projection'])
    return result, hashlib.sha256(path.read_bytes()).hexdigest()


def generate():
    rng=random.Random(19790918);ws=['',' ','\t','\r\n',' \t\n']
    values=['null','false','1.0e+0','"日本語😀é"','"\\u0061"',
            '{"integrity":[1,{"integrity":"quote \\\" , }"}]}','[[],{},true,"x\\\\y"]']
    rows=[]
    for n in range(1,7):
        for target in [None,*range(n)]:
            for variant in range(12):
                members=[]
                for j in range(n):
                    key=('"integrity"' if variant%2==0 else '"\\u0069ntegrity"') if j==target else json.dumps('key-'+str(j))
                    members.append((rng.choice(ws),key+rng.choice(ws)+':'+rng.choice(ws)+rng.choice(values),rng.choice(ws)))
                raw,p=assemble(members,target,lead=rng.choice(ws),trail=rng.choice(ws),prefix=rng.choice(ws),suffix=rng.choice(ws))
                a=json.loads(raw);a.pop('integrity',None);assert a==json.loads(p)
                rows.append(row('parts-'+str(n)+'-'+str(target)+'-'+str(variant),raw,p))
    calls,sourcehash=full_calls()
    return {'status':'author-constructed independent byte expectations, not independent reviewer clearance',
            'seed':19790918,'domain_hex':DOMAIN.hex(),'fixture_sha256':sourcehash,
            'component_vectors':rows,'full_call_vectors':calls}

if __name__=='__main__':
    encoded=(json.dumps(generate(),ensure_ascii=False,indent=2)+'\n').encode()
    target=HERE/'projection-vectors.json'
    if sys.argv[1:] == ['--write']:
        target.write_bytes(encoded)
    else:
        assert target.read_bytes()==encoded, 'saved oracle drift; never overwrite during tests'
        print('projection oracle regeneration: byte-identical')
