import assert from "node:assert/strict";
import { test } from "node:test";
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { jcsCanonicalize as jcs } from "../../reference/verifier/src/jcs.ts";
import {
  evaluateInner,
  evaluateInnerFiles,
  compareArithmetic,
  type InnerHarness,
} from "./inner-call.ts";
import { inspectLocalRecord, preparedArithmetic } from "./local-checks.ts";
import { GraphInvariantError } from "./dependencies.ts";
import {
  createBudget,
  readBounded,
  EXECUTION,
  InvocationError,
} from "./execution.ts";
import {
  BUNDLE,
  PROTOCOL,
  VERSION,
  makeReport,
  validateCompletion,
} from "./output.ts";

const read = (n: string) =>
  readFileSync(new URL(`./fixtures/${n}`, import.meta.url));
const expected = () => read("example-expected.json").toString();
const noop = () => {};
const options = { python: "/unavailable/python" };
function record() {
  const r = JSON.parse(read("example-record.jcs").toString());
  for (const k of ["$schema", "interpretation_bundle_id", "profile_id"])
    r[k] = r[k].replace("candidate.4", "candidate.5");
  r.payload.contract_id = r.payload.contract_id.replace(
    "candidate.4",
    "candidate.5",
  );
  return r;
}
function encode(r: any): Buffer {
  const { integrity, ...rest } = r;
  if (integrity)
    integrity.content_digest =
      "sha256:" +
      createHash("sha256")
        .update("nomue/record-content/v1\n")
        .update(jcs(rest))
        .digest("hex");
  return Buffer.from(jcs(r));
}
// Fixed historical expected numbers, never generated by the tested worker.
const fixed = JSON.parse(read("example-record.jcs").toString()).payload.result
  .adjusted;
const fixedReply = Buffer.from(
  JSON.stringify({
    adjusted_hex: fixed.map((r: any) => r.adjusted_hex),
    display_hex: fixed.map((r: any) => r.display_hex),
  }),
);
const harness: InnerHarness = { runner: async () => fixedReply };
const rows = (v: any) => [...v.conformance, ...v.verification];
const outcome = (v: any, stage: string) =>
  rows(v).find((r: any) => r.stage === stage);

test("successor schema and output are exact versions; candidate.4 never aliases candidate.5", async () => {
  const good = await evaluateInner(
    encode(record()),
    expected,
    options,
    harness,
  );
  assert.equal(good.protocol, PROTOCOL);
  assert.equal(good.interpretation_bundle_id, BUNDLE);
  assert.ok(rows(good).every((r: any) => r.outcome === "pass"));
  assert.deepEqual(good.input_evidence, { availability: "not_observed" });
  assert.ok(
    Object.values(good.guarantee_boundary).every((v) => v === "not_asserted"),
  );
  assert.equal(
    good.record_reference.stored_projection_digest,
    "sha256:27d66794b5e1225431b788f42ee094e0c4e2e89bf51176961d2289c8b9f8ee7c",
  );
  assert.equal(Object.hasOwn(good, "verified_bytes"), false);
  const old = await evaluateInner(
    read("example-record.jcs"),
    expected,
    options,
    harness,
  );
  assert.equal(old.refusal_kind, "unsupported_bundle");
});

test("pre-routing strict eligibility and bounds, then exact dispatch, then canonicalization", async () => {
  const cases: Array<[string, string]> = [
    ["{", "parse_error"],
    ['{"x":1,"x":2}', "parse_error"],
    ['{"x":1e999}', "routing_error"],
    ['{"interpretation_bundle_id":"bad","x":1e999}', "unsupported_bundle"],
  ];
  for (const [raw, kind] of cases) {
    const out = await evaluateInner(
      Buffer.from(raw),
      () => {
        throw Error("no read");
      },
      options,
      harness,
    );
    assert.equal(out.refusal_kind, kind);
    assert.equal(out.protocol, PROTOCOL);
    assert.equal(Object.hasOwn(out, "record_reference"), false);
  }
});

test("S fail returns scoped failure rows, never reads context or launches A", async () => {
  const r = record();
  r.payload = {};
  const out = await evaluateInner(
    encode(r),
    () => {
      throw Error("no read");
    },
    options,
    {
      runner: async () => {
        throw Error("no launch");
      },
    },
  );
  assert.equal(out.kind, "report");
  assert.equal(outcome(out, "S").outcome, "fail");
  assert.ok(
    rows(out)
      .slice(1)
      .every((r: any) => r.execution === "not_run"),
  );
});

test("K, D, I and C failures retain independently evaluated rows and block actual A launch", async () => {
  let launches = 0;
  const runner = async () => {
    launches++;
    return fixedReply;
  };
  const raw = encode(record());
  const e = JSON.parse(expected());
  e.revision_id = "urn:other";
  const out = await evaluateInner(
    Buffer.concat([raw, Buffer.from("\n")]),
    () => JSON.stringify(e),
    options,
    { runner },
  );
  assert.equal(launches, 0);
  assert.equal(outcome(out, "D").outcome, "pass");
  assert.equal(outcome(out, "H").outcome, "pass");
  assert.equal(outcome(out, "K").outcome, "fail");
  assert.equal(outcome(out, "C").outcome, "fail");
  assert.equal(outcome(out, "I").execution, "not_run");
  assert.deepEqual(outcome(out, "A").reasons, [
    "candidate:holm:stored_bytes_noncanonical",
    "candidate:holm:context_mismatch",
  ]);
  const r = record();
  r.payload.declaration.design.units[0].group_id = "missing";
  encode(r);
  r.integrity.content_digest = "sha256:" + "0".repeat(64);
  const crossed = await evaluateInner(Buffer.from(jcs(r)), expected, options, {
    runner,
  });
  assert.equal(launches, 0);
  assert.equal(outcome(crossed, "D").outcome, "fail");
  assert.equal(outcome(crossed, "I").outcome, "fail");
});

test("exact numerator mismatch cannot be hidden by unchanged display bits", async () => {
  const r = record();
  r.payload.result.adjusted[0].adjusted_hex = (
    BigInt("0x" + r.payload.result.adjusted[0].adjusted_hex) - 1n
  ).toString(16);
  const out = await evaluateInner(encode(r), expected, options, harness);
  assert.equal(outcome(out, "A").outcome, "fail");
  assert.deepEqual(outcome(out, "A").reasons, [
    "candidate:holm:exact_value_mismatch",
  ]);
});

test("malformed worker completion refuses, and arbitrary callback exceptions are internal", async () => {
  for (const reply of [
    Buffer.from("{"),
    Buffer.from("{}"),
    Buffer.from('{"adjusted_hex":[],"display_hex":[],"extra":1}'),
    Buffer.alloc(EXECUTION.workerBytes + 1),
  ]) {
    const out = await evaluateInner(encode(record()), expected, options, {
      runner: async () => reply,
    });
    assert.equal(out.refusal_kind, "internal_error");
    assert.equal(Object.hasOwn(out, "conformance"), false);
  }
  for (const error of [
    new TypeError("unexpected"),
    new SyntaxError("unexpected"),
    new GraphInvariantError("broken graph"),
  ]) {
    const out = await evaluateInner(
      encode(record()),
      () => {
        throw error;
      },
      options,
      harness,
    );
    assert.equal(out.refusal_kind, "internal_error");
  }
});

test("wire mutations and even graph-consistent fabricated S pass fail against private evidence", async () => {
  const edits = [
    (o: any) => {
      o.conformance[0].outcome = "fail";
    },
    (o: any) => {
      [o.conformance[0], o.verification[0]] = [
        o.verification[0],
        o.conformance[0],
      ];
    },
    (o: any) => {
      o.verification[2].scope.result_id = "other";
    },
    (o: any) => {
      o.record_reference.stored_projection_digest = "sha256:" + "0".repeat(64);
    },
    (o: any) => {
      o.verification[2].reasons = ["candidate:holm:context_mismatch"];
    },
    (o: any) => {
      o.protocol = "candidate.4";
    },
  ];
  for (const beforeValidate of edits)
    assert.equal(
      (
        await evaluateInner(encode(record()), expected, options, {
          ...harness,
          beforeValidate,
        })
      ).refusal_kind,
      "internal_error",
    );
  const r = record();
  r.payload = {};
  const local = inspectLocalRecord(encode(r), expected, noop, "candidate.5");
  const goodLocal = inspectLocalRecord(
    encode(record()),
    expected,
    noop,
    "candidate.5",
  );
  const fake = makeReport({
    local: goodLocal,
    arithmetic: { execution: "completed", outcome: "pass", reasons: [] },
  });
  fake.record_reference = makeReport({ local }).record_reference;
  assert.throws(() => validateCompletion(fake, { local }), GraphInvariantError);
});

test("late shared-budget failure supersedes a complete inner report", async () => {
  let late = false;
  const out = await evaluateInner(encode(record()), expected, options, {
    ...harness,
    beforeValidate: () => {
      late = true;
    },
    budget: {
      checkpoint() {
        if (late)
          throw new InvocationError("resource_limit", "processing_heap");
      },
      remainingMs: () => 5000,
    },
  });
  assert.equal(out.refusal_kind, "resource_limit");
  assert.equal(Object.hasOwn(out, "verification"), false);
  let now = 0;
  const budget = createBudget(undefined, { now: () => now, heap: () => 0 });
  now = 5000;
  budget.checkpoint();
  now = 5001;
  assert.throws(() => budget.checkpoint(), InvocationError);
  let heap = EXECUTION.heapBytes;
  const memory = createBudget(undefined, { now: () => 0, heap: () => heap });
  memory.checkpoint();
  heap++;
  assert.throws(() => memory.checkpoint(), InvocationError);
});

test("bounded file adapter checks actual bytes and preserves S-failure no-read behavior", async () => {
  const dir = mkdtempSync(join(tmpdir(), "holm-inner-"));
  try {
    const rp = join(dir, "record"),
      ep = join(dir, "expected"),
      small = join(dir, "small");
    writeFileSync(rp, encode(record()));
    writeFileSync(ep, expected());
    assert.equal(
      (await evaluateInnerFiles(rp, ep, options, harness)).kind,
      "report",
    );
    const missing = await evaluateInnerFiles(
      rp,
      join(dir, "missing"),
      options,
      harness,
    );
    assert.equal(outcome(missing, "C").execution, "error");
    const r = record();
    r.payload = {};
    writeFileSync(rp, encode(r));
    writeFileSync(ep, Buffer.alloc(1572865));
    assert.equal(
      (await evaluateInnerFiles(rp, ep, options, harness)).kind,
      "report",
    );
    writeFileSync(rp, encode(record()));
    assert.equal(
      (await evaluateInnerFiles(rp, ep, options, harness)).refusal_kind,
      "resource_limit",
    );
    for (const size of [7, 8, 9]) {
      writeFileSync(small, Buffer.alloc(size));
      if (size <= 8) assert.equal(readBounded(small, 8, noop).length, size);
      else assert.throws(() => readBounded(small, 8, noop), InvocationError);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("expected directory is C unreadable while Record-local passes remain", async () => {
  const dir = mkdtempSync(join(tmpdir(), "holm-expected-"));
  try {
    const rp = join(dir, "record");
    writeFileSync(rp, encode(record()));
    const out = await evaluateInnerFiles(rp, dir, options, harness);
    assert.equal(out.kind, "report");
    assert.equal(outcome(out, "C").execution, "error");
    assert.deepEqual(outcome(out, "C").reasons, [
      "candidate:holm:expected_unreadable",
    ]);
    assert.equal(Object.hasOwn(outcome(out, "C"), "outcome"), false);
    for (const stage of ["S", "K", "D", "H", "I"])
      assert.equal(outcome(out, stage).outcome, "pass");
    assert.equal(outcome(out, "A").execution, "not_run");
    assert.equal(
      (await evaluateInnerFiles(dir, rp, options, harness)).refusal_kind,
      "input_access_error",
    );
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("cancellation is an invocation refusal; copied arithmetic cannot rewrite private inspected data", async () => {
  const ac = new AbortController();
  ac.abort();
  const out = await evaluateInner(
    encode(record()),
    expected,
    { ...options, signal: ac.signal },
    harness,
  );
  assert.equal(out.refusal_kind, "execution_cancelled");
  const local = inspectLocalRecord(
    encode(record()),
    expected,
    noop,
    "candidate.5",
  );
  const first = preparedArithmetic(local)!;
  first.submitted[0].adjusted_hex = "0";
  assert.notEqual(preparedArithmetic(local)!.submitted[0].adjusted_hex, "0");
  assert.equal(preparedArithmetic(structuredClone(local)), undefined);
  assert.equal(
    compareArithmetic(fixedReply, preparedArithmetic(local)!, noop).execution,
    "completed",
  );
});

const python = process.env.NOMUE_TEST_PYTHON;
test(
  "actual isolated Python worker agrees with retained fixed results",
  { skip: !python },
  async () => {
    const out = await evaluateInner(encode(record()), expected, {
      python: python!,
    });
    assert.equal(out.kind, "report");
    assert.equal(outcome(out, "A").outcome, "pass");
    const out2 = await evaluateInner(
      encode(record()),
      expected,
      { python: python! },
      { budget: { checkpoint: noop, remainingMs: () => 1 } },
    );
    assert.equal(out2.refusal_kind, "resource_limit");
    const ac = new AbortController();
    const running = evaluateInner(encode(record()), expected, {
      python: python!,
      signal: ac.signal,
    });
    setTimeout(() => ac.abort(), 1);
    assert.equal((await running).refusal_kind, "execution_cancelled");
  },
);
